version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 app.py
  test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
